Fast fix for ts compile error.
With newer versions of Typescript when running `npm run server` webpack will throw an error (`TypeError: TS.parseConfigFile is not a function`). This is a fast fix for it, so it works.